### ISSUE TITLE
why not 3rd party?

### ISSUE THREAD

**Issue by flying-sheep** [juancarlospaco/boilerplatembed#2]
* publish to pypi
* create a build script like this:

```py
import tarfile
import shutil
import zipapp
import urllib.request

version = get_newest_boilerplate_version()  # write this

MODULE = 'unicodemoticon'  # or something
BOILERPLATE_URL = 'https://pypi.python.org/packages/source/j/j-boilerplate/j-boilerplate-{}.tar.gz'.format(version)

DIST = Path('dist')
DIST.mkdir()

name, * = urllib.request.urlretrieve(BOILERPLATE_URL)
with tarfile.open(name) as tgz:
	tgz.extract('boilerplate.py', str(DIST))

shutil.copytree(MODULE, str(DIST / MODULE))

zipapp.create_archive(MODULE, DIST, '/usr/bin/env python3', MODULE + '.__main__:main')
```

in the end you’ll have a zippapp containing the newest version of your boilerplate, *and* you can reason about what ends up in your main program because you `from boilerplate import foo, bar`

**Comment by juancarlospaco** [comment]
@flying-sheep https://github.com/ellisonbg/antipackage#antipackage :grey_question:

**Comment by flying-sheep** [comment]
hmm, i’d never use something like that in a production release.

it’s cool for quick tests and scripts though!

**Comment by juancarlospaco** [comment]
The idea is to make a script that builds an on demand custom boilerplate for you, 
starting from a base that only has a Logger (because print dont really work with unicode) and imports,
then it asks the user for `Y/N` with a Default selection, if hir want to add that feature, 
how many lines it will add to the boilerplate, a logical sorting order, a description.

Imagine:
```
juan@pc$ python3 boilerplatembed.py

Welcome to BoilerplatEmbed, all the features only require Python 3 Standard Library.

I want my Script/App To...

Have Crossplatform Clipboard Copy and Paste.
(This feature adds 15 Lines of code to Boilerplate)
[Y / n] ? Y
Ok.

Have Crossplatform Asynchronous MultiThreading Decorator for blocking Functions.
(This feature adds 22 Lines of code to Boilerplate)
[Y / n] ? _
```

This will output a normal `*.py` and a stealth string 1 line `*.py` file, on the disk (not on PyPI),
with a list of functions on the namespace and a `# Write your code Below` where you can write.

But even the boilerplatembed itself can end up on PyPI too.
Then anyone can send a pull request with a new feature, if it only needs Python3 std lib.
Output will not be autogenerated code, but human code (concatenated) according your chosen features.

Feedback welcome @flying-sheep 

:smile_cat:

**Comment by flying-sheep** [comment]
what’s the problem with simply putting it onto PyPI, installing it globally on your system, and putting it in the dependencies of every one of your projects?

this way you won’t have to do a thing and let pip handle everything, will always have the newest version instead of having to fix bugs, and there will be no confusing boilerplate in your scripts/programs

**Comment by juancarlospaco** [comment]
Thats basically cookie-cutter, try it, it doesnt cut it for me.

They track all on requirements and git, 
they have a lot of "templates", templates have hundred dependencies, some broken, 
they add lots of stuff not pip-installable to a git repo, so you clone an empty template from a git repo, 
it comes with angularJS, bootstrap, themes, Jquery, etc that I dont want.
Git cloning repos just to get a template. Git repos have recursive sub-repos.
Keeping track of hundred of dependencies is complicated, which one breaks, which one is old.
Std lib never breaks, Std lib never is old, Std lib dont require git repos.
No cookie-cutter works with std lib. I end up removing more stuff than I add.

This will be put on PyPI, installing it globally on your system, and doesnt even need dependencies.
will always have the newest version, because is std lib, and there will be no confusing boilerplate in your scripts/programs because all will be a 1 line stealth string.

**Comment by juancarlospaco** [comment]
We are going this way...


![screenshot_20160210_033556](https://cloud.githubusercontent.com/assets/1189414/12940472/38f29aa8-cfa8-11e5-9b61-23da8355c84b.jpg)


For something more complex get https://boltons.readthedocs.org or http://cookiecutter.readthedocs.org

**Comment by flying-sheep** [comment]
i think you’ll change your mind once you have made the 4th modification in your boilerplate code and have manually gone through all your projects to change it…
